### ISSUE TITLE
Test the mk2 main board

### ISSUE THREAD

**Issue by Iacobacci** [ManufacturedMotion/Hexapod#100]
Confirm the following works:

- [x] Voltage divider outputs a voltage within the acceptable range for the pins
- [x] pi can control LED ring 
- [x] pi can talk to teensy
- [x] pi can control fan
- [x] voltage divider sends correct value to teensy (battery reading)
- [x] new board can control servos

**Comment by DillonKane** [comment]
can measure temp for fan control logic with "sudo vcgencmd measure_temp"

**Comment by DillonKane** [comment]
voltage divider needs to be multiplied by offset of 0.01606 to get correct reading

**Comment by DillonKane** [comment]
voltage divider sends vdd of 2.45 with battery vdd of 12.3V

**Comment by zschwid** [comment]
Can we get a status update here?

**Comment by DillonKane** [comment]
Pi can control LED ring if jumper connector is used for LED signal wire. Jumper connects SIG to Pi pin MOSI SCLK0.

Will be addressed with PCB redesign
