### ISSUE TITLE
Update Servo Mounts

### ISSUE THREAD

**Issue by DillonKane** [ManufacturedMotion/Hexapod#12]
update screw spacing on all servo mounts so all 4 screws can be used

**Comment by Diacoba1** [comment]
Cleared assignees -- we should only assign to one person so we know who is tackling it

**Comment by Diacoba1** [comment]
I have already updated S1, and S2. The final change needs to be done for S3. But we should lump it in with the toe fixes

**Comment by Diacoba1** [comment]
- [ ] Update S1 Motor mount to not have an overhang
- [ ] Check out S3 spacing
