### ISSUE TITLE
Voltage drops momentarily when all motors make collision, causing the RPi to shutdown due to undervoltage

### ISSUE THREAD

**Issue by zschwid** [ManufacturedMotion/Hexapod#126]
Fixes to try:
- Add bulk / decoupling capacitance
- Bigger buck converter

**Comment by Iacobacci** [comment]
We are going to remediate this with a PCB re-design to run the servos independently off the battery, with the Buck converter being dedicated to the Pi, Fan, LEDs, and other peripherals. Tracked In #130
